development:
  adapter: redis
  url: <%= Rails.application.credentials.redis_url %>

test:
  adapter: test
  url: <%= Rails.application.credentials.redis_url %>

production:
  adapter: redis
  url: <%= Rails.application.credentials.redis_url %>
  channel_prefix: lightning_rails_production
