default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= Rails.application.credentials.database_url %>

development:
  <<: *default
  database: rapid_rails_development

test:
  <<: *default
  database: rapid_rails_test

production:
  <<: *default
  database: rapid_rails_production
