default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: lightning_rails_development
  url: <%= Rails.application.credentials.database_url %>

test:
  <<: *default
  database: lightning_rails_test

production:
  <<: *default
  database: lightning_rails_production
  url: <%= Rails.application.credentials.database_url %>
