service: lightning_rails
image: hetsketch/lightning_rails

ssh:
  user: www

servers:
  web:
    hosts:
      - <%= ENV["DEPLOY_HOST"] %>
    options:
      add-host: host.docker.internal:host-gateway
      memory: 512M

registry:
  username: hetsketch
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  remote:
    arch: amd64
  args:
    RUBY_VERSION: '3.3.6'
    NODE_VERSION: 22
    YARN_VERSION: '1.22.22'
    RAILS_ENV: production

env:
  clear:
    RAILS_LOG_TO_STDOUT: 1
    RAILS_SERVE_STATIC_FILES: 1
    RAILS_ENV: production
  secret:
    - RAILS_MASTER_KEY

accessories:
  postgres:
    image: postgres:17
    host: <%= ENV["DEPLOY_HOST"] %>
    port: 5432
    env:
      clear:
        POSTGRES_DB: lightning_rails_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2
    host: <%= ENV["DEPLOY_HOST"] %>
    cmd: redis-server --requirepass <%= ENV["REDIS_PASSWORD"] %> --replica-read-only no
    env:
      secret:
        - REDIS_PASSWORD
    directories:
      - redis_data:/data
  options:
    network: "private"

traefik:
  args:
    accesslog: true
    accesslog.format: json
  labels:
    traefik.http.middlewares.test-compress.compress: true
    traefik.http.middlewares.cache-headers.headers.customresponseheaders.Cache-Control: public,max-age=2592000
  options:
    network: "private"

healthcheck:
  path: /up
  interval: 10s
