service: lightning_rails
image: k0va1/lightning_rails

ssh:
  user: www

registry:
  server: ghcr.io
  username: k0va1
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  args:
    RUBY_VERSION: "3.3.6"
    NODE_VERSION: "20.18.1"
    YARN_VERSION: "1.22.22"
    RAILS_ENV: "production"
  secrets:
    - RAILS_MASTER_KEY

servers:
  web:
    hosts:
      - <prod_ip>
    options:
      memory: 512M

  worker:
    hosts:
      - <prod_ip>
    options:
      memory: 2048M
    cmd: bundle exec sidekiq -C config/sidekiq.yml

env:
  clear:
    RAILS_LOG_TO_STDOUT: 1
    RAILS_SERVE_STATIC_FILES: 1
    RAILS_ENV: production
  secret:
    - RAILS_MASTER_KEY

accessories:
  postgres:
    image: postgres:17
    hosts:
      - <prod_ip>
    env:
      clear:
        POSTGRES_DB: lightning_rails_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    hosts:
      - <prod_ip>
    cmd: "/bin/sh -c 'redis-server --requirepass $REDIS_PASSWORD' --replica-read-only no"
    env:
      secret:
        - REDIS_PASSWORD
    directories:
      - redis_data:/data

proxy:
  ssl: false
  app_port: 3000
  forward_headers: true
  healthcheck:
    interval: 3
    path: /up
    timeout: 3
  logging:
    request_headers:
      - Cache-Control
      - X-Forwarded-Proto
    response_headers:
      - X-Request-ID
      - X-Request-Start

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"
