# Name of your application. Used to uniquely configure containers.
service: rapid_rails

# Name of the container image.
image: hetsketch/rapid_rails

# Deploy to these servers.
servers:
  web:
    hosts:
      - <prod_ip>
    options:
      add-host: host.docker.internal:host-gateway

# Credentials for your image host.
registry:
  username: hetsketch
  password:
    - MRSK_REGISTRY_PASSWORD

ssh:
  user: www

builder:
  args:
    RUBY_VERSION: '3.2.2'
    NODE_VERSION: '18.12.0'
    YARN_VERSION: '1.22.15'
    RAILS_ENV: production
  multiarch: false

env:
  clear:
    RAILS_LOG_TO_STDOUT: 1
    RAILS_SERVE_STATIC_FILES: 1
    RAILS_ENV: production
  secret:
    - RAILS_MASTER_KEY

accessories:
  postgres:
    image: postgres:15.0
    host: <prod_ip>
    port: 5432
    env:
      clear:
        POSTGRES_DB: rapid_rails_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis:7.0
    port: 6379
    directories:
      - redis_data:/data

traefik:
  args:
    accesslog: true
    accesslog.format: json

healthcheck:
  path: /up
