service: lightning_rails
image: hetsketch/lightning_rails

servers:
  web:
    hosts:
      - <%= ENV["DEPLOY_HOST"] %>
    options:
      add-host: host.docker.internal:host-gateway
      memory: 512M

registry:
  username: hetsketch
  password:
    - KAMAL_REGISTRY_PASSWORD

ssh:
  user: www

builder:
  multiarch: false
  args:
    RUBY_VERSION: '3.2.2'
    NODE_VERSION: '18.12.0'
    YARN_VERSION: '1.22.15'
    RAILS_ENV: production

env:
  clear:
    RAILS_LOG_TO_STDOUT: 1
    RAILS_SERVE_STATIC_FILES: 1
    RAILS_ENV: production
  secret:
    - RAILS_MASTER_KEY

accessories:
  postgres:
    image: postgres:15.0
    host: <%= ENV["DEPLOY_HOST"] %>
    port: 5432
    env:
      clear:
        POSTGRES_DB: lightning_rails_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis:7.0
    host: <%= ENV["DEPLOY_HOST"] %>
    port: 6379
    directories:
      - redis_data:/data

traefik:
  args:
    accesslog: true
    accesslog.format: json
  labels:
    traefik.http.middlewares.test-compress.compress: true
    traefik.http.middlewares.cache-headers.headers.customresponseheaders.Cache-Control: public,max-age=2592000

healthcheck:
  path: /up
  interval: 10s
